#spring:
#  security:
#    user:
#      name: admin
#      password: pcf123
security:
  basic:
    enabled: false
management:
  security:
    enabled: false
---
spring:
  profiles: lower

logging:
  level:
    root: info

